[package]
name = "k-solder"
version = "0.1.0"
authors = ["Qingluan <you@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minreq = "2.1.0"
httpcodec = "0.2.3"